apiVersion: apps/v1
kind: Deployment
metadata:
  name: njil
spec:
  replicas: 1
  selector:
    matchLabels:
      app: njil
  template:
    metadata:
      labels:
        app: njil
    spec:
      containers:
      - image: okteto.dev/njil:latest
        name: njil
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.crazygames.com"
        - name: Vless_UUID
          value: "5d8675a1-8244-48f5-952c-8abeb78dba9b"
        - name: Vless_Path
          value: "/ss33"
        - name: Vmess_UUID
          value: "5d8675a1-8244-48f5-952c-8abeb78dba9b"
        - name: Vmess_Path
          value: "/S44"
        - name: Share_Path
          value: "/Share34"
