apiVersion: apps/v1
kind: Deployment
metadata:
  name: eedc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eedc
  template:
    metadata:
      labels:
        app: eedc
    spec:
      containers:
      - image: okteto.dev/eedc:latest
        name: eedc
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.crazygames.com"
        - name: Vless_UUID
          value: "d4037c88-6086-439f-bd9d-3d313956d3b8"
        - name: Vless_Path
          value: "/ss33"
        - name: Vmess_UUID
          value: "d4037c88-6086-439f-bd9d-3d313956d3b8"
        - name: Vmess_Path
          value: "/S44"
        - name: Share_Path
          value: "/Share34"
